USE EMSDB;

CREATE TABLE tbl_bbs(
	BBS_ID	BIGINT PRIMARY KEY AUTO_INCREMENT,
	BBS_P_ID	BIGINT	DEFAULT 0,
	BBS_WRITER	VARCHAR(50)	NOT NULL,	
	BBS_DATE	VARCHAR(10),		
	BBS_TIME	VARCHAR(10),	
	BBS_SUBJECT	VARCHAR(125),		
	BBS_CONTENT	VARCHAR(1000),		
	BBS_COUNT	INT	DEFAULT 0	

);

drop table tbl_bbs ;
DESC tbl_bbs;

commit;